---
abstract: 'client and server implementation of XML-RPC protocol'
author:
  - 'Paul Kulchenko (paulclinger@yahoo.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XMLRPC-Lite
no_index:
  directory:
    - t
    - inc
requires:
  SOAP::Lite: 0.716
  SOAP::Transport::TCP: 0.715
version: 0.717
